// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BDDT.BoardBuffer
{

using global::System;
using global::FlatBuffers;

public struct iVec2 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public iVec2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint X { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public uint Y { get { return __p.bb.GetUint(__p.bb_pos + 4); } }

  public static Offset<iVec2> CreateiVec2(FlatBufferBuilder builder, uint X, uint Y) {
    builder.Prep(4, 8);
    builder.PutUint(Y);
    builder.PutUint(X);
    return new Offset<iVec2>(builder.Offset);
  }
};


}
