// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BDDT.BoardBuffer
{

public enum TileType : sbyte
{
 tree = 0,
 grass = 1,
 sand = 2,
 ice = 3,
 water = 4,
};


}
